# Generated by Django 3.2.5 on 2022-09-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20220905_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('school_class', models.CharField(max_length=120)),
            ],
        ),
    ]
