# Generated by Django 3.2.5 on 2022-09-21 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_comments',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='scheme',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='textbooks',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabusupload',
            name='scheme',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='syllabusupload',
            name='textbooks',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='teacherupload',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
