# Generated by Django 3.2.5 on 2022-12-23 09:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_auto_20220921_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_comments',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='scheme',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='textbooks',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='syllabusupload',
            name='scheme',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='syllabusupload',
            name='textbooks',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='teacherupload',
            name='audio',
            field=models.FileField(blank='True', default='', null='', upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='teacherupload',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='teacherupload',
            name='videos',
            field=models.FileField(blank='True', default='', null='True', upload_to='video'),
        ),
    ]
