# Generated by Django 3.2.5 on 2022-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20221223_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='audio',
            field=models.FileField(blank='True', default='media/audio/aud1', null='', upload_to='audio'),
        ),
    ]
