# Generated by Django 3.2.5 on 2022-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_alter_teacherupload_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='videos',
            field=models.FileField(blank='True', default='', null='', upload_to='video'),
        ),
    ]
