# Generated by Django 3.2.5 on 2022-12-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_alter_teacherupload_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherupload',
            name='videos',
            field=models.FileField(blank='True', default='media/video/vid1', null='', upload_to='video'),
        ),
    ]
