# Generated by Django 3.2.5 on 2023-01-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_alter_teacherupload_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_comments',
            name='name',
            field=models.CharField(default='user.userna  me', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_term',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('english', 'english'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('economics', 'economics'), ('accounts', 'accounts'), ('government', 'government'), ('literature', 'literature'), ('geography', 'geography'), ('futher-maths', 'futher-maths')], default='', max_length=60),
        ),
    ]
