# Generated by Django 3.2.5 on 2023-01-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20230113_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_term',
            field=models.CharField(choices=[('1ST TERM', '1ST TERM'), ('2ND TERM', '2ND TERM'), ('3RD TERM', '3RD TERM')], default='', max_length=60),
        ),
    ]
