# Generated by Django 3.2.5 on 2023-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_alter_syllabus_syllabus_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_comments',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
