# Generated by Django 3.2.5 on 2023-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_alter_add_comments_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SyllabusUpload',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_term',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_subject',
            field=models.CharField(choices=[('mathematics', 'mathematics'), ('english', 'english'), ('physics', 'physics'), ('chemistry', 'chemistry'), ('biology', 'biology'), ('economics', 'economics'), ('accounts', 'accounts'), ('government', 'government'), ('literature', 'literature'), ('geography', 'geography'), ('futher-maths', 'futher-maths')], default='', max_length=60),
        ),
    ]
