# Generated by Django 3.2.5 on 2023-03-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_syllabus_syllabus_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=240)),
                ('date', models.DateTimeField(default='')),
                ('description', models.CharField(max_length=1200)),
                ('link', models.CharField(max_length=120)),
            ],
        ),
    ]
