# Generated by Django 3.2.5 on 2023-03-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(max_length=1200),
        ),
    ]
